---
- hosts: appservers
  tasks:
  - name: creting file
    file: dest=/home/ssm-user/file.txt state=touch

  - name: file permissions
    file: dest=/home/ssm-user/file.txt mode=0777 owner=root group=root
    become: yes

  - name: creating directory
    file: dest=/home/ssm-user/temp/ state=directory

  - name: creating multiple directories
    file: dest=/home/ssm-user/temp/{{item}} state=directory
    with_items:
        - dir1
        - dir2
